### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by w33ha-zxc** [konstruktoid/konstruktoid#1]
Executing the hardening procedure deletes the home directories for all the users on the system causing loops at the login window.

Recreated the scenario almost a dozen times before catching the issue going through logs.

executing mkhomedir_helper from recovery mode fixes the issue

HyperV Version: 10.0.17763.1
Replicated for Both Ubuntu 20.04 LTS and Ubuntu 22.04 LTS flavors

![image](https://user-images.githubusercontent.com/19168627/183772271-3d848765-a3cd-4eb3-9db5-a1d5f1b7d7c9.png)
![image](https://user-images.githubusercontent.com/19168627/183772508-88b07133-6ea0-4a62-be38-91690086f725.png)

**Comment by konstruktoid** [comment]
Hi @w33ha-zxc, please open the issue in the correct project.
Is this related to https://github.com/konstruktoid/hardening or https://github.com/konstruktoid/ansible-role-hardening?
